print("Bienvenido a mi primer programa")
print("Tipo entero")
print(type(38))
print("Tipo flotante")
print((type(23.43)))
print("Tipo cadena")
print(type("Hola"))
print("Tipo booleano")
print(type(True))